language: ruby
rvm:
- 2.1
script:
- npm install
- grunt deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAJK5VH3XKJ34424UQ
  secret_access_key:
    secure: "ftk6/CkME/AQ9LWO7EE+6SmOheeizCN9zTIxjXcPYdvFAGF6P7Oy1ho6OIOUcn5GavNg4Yes+idAwKJrs7ktjSw6b0vNFG9iHL/W9HBOXOC9V0DkPJHvA7PtNHVzE2xaKNSg4/NTEsPw6HlH/L5tG4Rjzr5i0Sx6BAwlRzAjswk="
  bucket: informatics-blog
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  on:
    branch: master
