#--------------
# Site settings
#--------------

title:         Met Office Informatics Lab
email:         met-office-lab@gmail.com
author:        Met Office Lab
short_description: "A lab at the Met Office for creating things!"
description:   "The Met Office Informatics Lab combines scientists, software engineers, and designers to create new things. We try to rapidly prototype non-business-as-usual ideas that allow people from within the Met Office (and beyond) to make our science and data useful."
baseurl:       ""
url:           "http://www.informaticslab.co.uk/"
github-url:    "http://github.com/met-office-lab/"
twitter-url:   "http://twitter.com/metolab/"
instagram-url: "http://instagram.com/informaticslab/"
calendar-url:  "/get-involved/calendar.html"
image-bin:     "http://s3-eu-west-1.amazonaws.com/informatics-webimages/"


# Google analytics
google_analytics: 'UA-60337429-1'


#-----------
#Build stuff
#-----------

#markdown options
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks"]

#build output dir
destination: _site

#exclude from build
exclude: ["bower.json",
          "Gemfile*",
          "package.json",
          "README.md",
          "LICENSE.md",
          "Gruntfile.js",
          "node_modules",
          "bower_components",
          "tests"]

#sass config
sass:
  sass_dir: _sass
  style: compressed

#pagination
#paginate: 2
post_limit: 3
default_blog_thumbnail: "/img/about/2.jpg"

collections:
    profiles:
        output: true
    projects:
        output: true
    posts:
        output: true
